--Template

INSERT INTO [dbo].[Books] ([AuthorId],[DetailsEN],[Discount],[GenreId],[Name],[Picture],[PublisherId],[Pages],[Price],[Published],[Quantity]) 
VALUES(AUTHOR,N'DETAILS',DISCOUNT,GENRE,N'NAME',N'images/books/PICTURE.jpg',PUBLISHER,PAGES,PRICE,1,QUANTITY);

--Arnaldur Indridason

INSERT INTO [dbo].[Books] ([AuthorId],[DetailsEN],[Discount],[GenreId],[Name],[Picture],[PublisherId],[Pages],[Price],[Published],[Quantity]) 
VALUES(14,N'A man is found murdered in his Reykjavik flat. There are no obvious clues apart from a cryptic note left on the body and a photograph of a young girl''s grave. Delving into the dead man''s life Detective Erlendur discovers that forty years ago he was accused of an appalling crime, but never convicted. Had his past come back to haunt him? As Erlendur struggles to build a relationship with his unhappy daughter, his investigation takes him to Iceland''s Genetic Research Centre, where he uncovers disturbing secrets that are even darker than the murder of an old man. Jar City is the first book in the series starring Detective Erlendur available in English',0,7,N'Jar City',N'images/books/jarCity.jpg',7,352,1200,1,15);

INSERT INTO [dbo].[Books] ([AuthorId],[DetailsEN],[Discount],[GenreId],[Name],[Picture],[PublisherId],[Pages],[Price],[Published],[Quantity]) 
VALUES(14,N'THE LIVING! Erlendur has recently joined the police force as a young officer and immediately sinks into the darkness of Reykjavik''s underworld. Working nights, he discovers the city is full of car crashes, robberies, drinkers and fighters. And sometimes an unexplained death. THE LOST! A homeless man Erlendur knows is found drowned. But few people care. Or when a young woman on her way home from a club vanishes. Both cases go cold. ',0,7,N'Reykjavik Nights',N'images/books/reykjavikNights.jpg',7,304,1200,1,15);

INSERT INTO [dbo].[Books] ([AuthorId],[DetailsEN],[Discount],[GenreId],[Name],[Picture],[PublisherId],[Pages],[Price],[Published],[Quantity]) 
VALUES(14,N'A missing woman. A missing boy. Detective Erlendur returns - for the last time. A young woman walks into the frozen fjords of Iceland, never to be seen again. But Matthildur leaves in her wake rumours of lies, betrayal and revenge. Decades later, somewhere in the same wilderness, Detective Erlendur is on the hunt. He is looking for Matthildur but also for a long-lost brother, whose disappearance in a snow-storm when they were children has coloured his entire life. He is looking for answers. Slowly, the past begins to surrender its secrets. But as Erlendur uncovers a story about the limits of human endurance, he realises that many people would prefer their crimes to stay buried. ',0,7,N'Strange Shores',N'images/books/strangeShores.jpg',7,304,1200,1,15);

INSERT INTO [dbo].[Books] ([AuthorId],[DetailsEN],[Discount],[GenreId],[Name],[Picture],[PublisherId],[Pages],[Price],[Published],[Quantity]) 
VALUES(14,N'One cold autumn night, a woman is found hanging from a beam at her holiday cottage. At first sight, it appears like a straightforward case of suicide; Maria had never recovered from the death of her mother two years previously and she had a history of depression. But then the friend who found her body approaches Detective Erlendur with a tape of a seance that Maria attended before her death and his curiosity is aroused. Driven by a need to find answers, Erlendur begins an unofficial investigation into Maria''s death. But he is also haunted by another unsolved mystery - the disappearance of two young people thirty years ago - and by his own quest to find the body of his brother, who died in a blizzard when he was a boy. Hypothermia is Indridason''s most compelling novel yet. ',0,7,N'Hypothermia',N'images/books/hypothermia.jpg',7,336,1200,1,15);

INSERT INTO [dbo].[Books] ([AuthorId],[DetailsEN],[Discount],[GenreId],[Name],[Picture],[PublisherId],[Pages],[Price],[Published],[Quantity]) 
VALUES(14,N'From Gold Dagger Award--winning author Arnaldur Indridason comes a Reykjavik thriller introducing Inspector Erlendur. When a lonely old man is found dead in his Reykjavik flat, the only clues are a cryptic note left by the killer and a photograph of a young girl''s grave. Inspector Erlendur discovers that many years ago the victim was accused, but not convicted, of an unsolved crime, a rape. Did the old man''s past come back to haunt him? As Erlendur reopens this very cold case, he follows a trail of unusual forensic evidence, uncovering secrets that are much larger than the murder of one old man. An international sensation, the Inspector Erlendur series has sold more than two million copies worldwide.',0,7,N'Jar City',N'images/books/jarCityStMartin.jpg',8,289,1200,1,15);

-- Halldor Laxness

INSERT INTO [dbo].[Books] ([AuthorId],[DetailsEN],[Discount],[GenreId],[Name],[Picture],[PublisherId],[Pages],[Price],[Published],[Quantity]) 
VALUES(13,N'First published in 1946, this humane epic novel is set in rural Iceland in the early twentieth century. Bjartus is a sheep farmer determined to eke a living from a blighted patch of land. Nothing, not merciless weather, nor his family will come between him and his goal of financial independence. Only Asta Solillja, the child he brings up as his daughter, can pierce his stubborn heart. As she grows up, keen to make her own way in the world, Bjartus'' obstinacy threatens to estrange them forever. ',10,6,N'Independent People',N'images/books/independentPeople.jpg',7,576,1500,1,20);

INSERT INTO [dbo].[Books] ([AuthorId],[DetailsEN],[Discount],[GenreId],[Name],[Picture],[PublisherId],[Pages],[Price],[Published],[Quantity]) 
VALUES(13,N'Abandoned as a baby, Alfgrimur is content to spend his days as a fisherman living in the turf cottage outside Reykjavik with the elderly couple he calls grandmother and grandfather. There he shares the mid-loft with a motley bunch of eccentrics and philosophers who find refuge in the simple respect for their fellow men that is the ethos at the Brekkukot. But the narrow horizons of Alfgrimur''s idyllic childhood are challenged when he starts school and meets Iceland''s most famous singer, the mysterious Garoar Holm. Garoar encourages him to aim for the ''one true note'', but how can he attain it without leaving behind the world that he loves? ',10,6,N'Fish Can Sing',N'images/books/fishCanSing.jpg',7,256,1500,1,20);

-- George R.R. Martin

INSERT INTO [dbo].[Books] ([AuthorId],[DetailsEN],[Discount],[GenreId],[Name],[Picture],[PublisherId],[Pages],[Price],[Published],[Quantity]) 
VALUES(12,N'The first volume of A Song of Ice and Fire, the greatest fantasy epic of the modern age. GAME OF THRONES is now a major TV series from HBO, starring Sean Bean. Summers span decades. Winter can last a lifetime. And the struggle for the Iron Throne has begun. As Warden of the north, Lord Eddard Stark counts it a curse when King Robert bestows on him the office of the Hand. His honour weighs him down at court where a true man does what he will, not what he must ...and a dead enemy is a thing of beauty. The old gods have no power in the south, Stark''s family is split and there is treachery at court. Worse, the vengeance-mad heir of the deposed Dragon King has grown to maturity in exile in the Free Cities. He claims the Iron Throne.',0,3,N'A Game of Thrones',N'images/books/aGameOfThrones.jpg',5,864,1500,1,20);

INSERT INTO [dbo].[Books] ([AuthorId],[DetailsEN],[Discount],[GenreId],[Name],[Picture],[PublisherId],[Pages],[Price],[Published],[Quantity]) 
VALUES(12,N'The second volume of A Song of Ice and Fire, the greatest fantasy epic of the modern age. GAME OF THRONES is now a major TV series from HBO, featuring a stellar cast. Throughout Westeros, the cold winds are rising. From the ancient citadel of Dragonstone to the forbidding lands of Winterfell, chaos reigns as pretenders to the Iron Throne of the Seven Kingdoms stake their claims through tempest, turmoil and war.',0,3,N'A Clash of Kings',N'images/books/aClashOfKings.jpg',5,928,1500,1,20);

INSERT INTO [dbo].[Books] ([AuthorId],[DetailsEN],[Discount],[GenreId],[Name],[Picture],[PublisherId],[Pages],[Price],[Published],[Quantity]) 
VALUES(12,N'HBO''s hit series A GAME OF THRONES is based on George R. R. Martin''s internationally bestselling series A SONG OF ICE AND FIRE, the greatest fantasy epic of the modern age. A FEAST FOR CROWS is the fourth volume in the series. The Lannisters are in power on the Iron Throne. The war in the Seven Kingdoms has burned itself out, but in its bitter aftermath new conflicts spark to life. The Martells of Dorne and the Starks of Winterfell seek vengeance for their dead. Euron Crow''s Eye, as black a pirate as ever raised a sail, returns from the smoking ruins of Valyria to claim the Iron Isles.',0,3,N'A Feast for Crows',N'images/books/aFeastForCrows.jpg',5,864,1500,1,20);

--E.L.James

INSERT INTO [dbo].[Books] ([AuthorId],[DetailsEN],[Discount],[GenreId],[Name],[Picture],[PublisherId],[Pages],[Price],[Published],[Quantity]) 
VALUES(11,N'Romantic, liberating and totally addictive, `Fifty Shades of Grey` is a novel that will obsess you, possess you, and stay with you forever. When literature student Anastasia Steele interviews successful entrepreneur Christian Grey, she finds him very attractive and deeply intimidating. Convinced that their meeting went badly, she tries to put him out of her mind - until he turns up at the store where she works part-time, and invites her out. Unworldly and innocent, Ana is shocked to find she wants this man. And, when he warns her to keep her distance, it only makes her want him more. But Grey is tormented by inner demons, and consumed by the need to control. As they embark on a passionate love affair, Ana discovers more about her own desires, as well as the dark secrets Grey keeps hidden away from public view... ',5,8,N'Fifty Shades of Grey',N'images/books/fiftyShadesOfGrey.jpg',6,528,1500,1,15);

INSERT INTO [dbo].[Books] ([AuthorId],[DetailsEN],[Discount],[GenreId],[Name],[Picture],[PublisherId],[Pages],[Price],[Published],[Quantity]) 
VALUES(11,N'Romantic, liberating and totally addictive, the Fifty Shades trilogy will obsess you, possess you, and stay with you for ever ... Daunted by the dark secrets of the tormented young entrepreneur Christian Grey, Ana Steele has broken off their relationship to start a new career with a US publishing house. But desire for Grey still dominates her every waking thought, and when he proposes a new arrangement, she cannot resist. Soon she is learning more about the harrowing past of her damaged, driven and demanding Fifty Shades than she ever thought possible. But while Grey wrestles with his inner demons, Ana must make the most important decision of her life. And it''s a decision she can only make on her own ... ',5,8,N'Fifty Shades Darker',N'images/books/fiftyShadesDarker.jpg',6,567,1500,1,15);

INSERT INTO [dbo].[Books] ([AuthorId],[DetailsEN],[Discount],[GenreId],[Name],[Picture],[PublisherId],[Pages],[Price],[Published],[Quantity]) 
VALUES(11,N'Romantic, liberating and totally addictive, the Fifty Shades trilogy will obsess you, possess you and stay with you for ever. When Ana Steele first encountered the driven, damaged entrepreneur Christian Grey, it sparked a sensual affair that changed both their lives irrevocably. Ana always knew that loving her Fifty Shades would not be easy, and being together poses challenges neither of them had anticipated. Ana must learn to share Grey''s opulent lifestyle without sacrificing her own integrity or independence; and Grey must overcome his compulsion to control and lay to rest the horrors that still haunt him. Now, finally together, they have love, passion, intimacy, wealth, and a world of infinite possibilities. But just when it seems that they really do have it all, tragedy and fate combine to make Ana''s worst nightmares come true ...',5,8,N'Fifty Shades Freed',N'images/books/fiftyShadesFreed.jpg',6,567,1500,1,10);

--Agatha

INSERT INTO [dbo].[Books] ([AuthorId],[DetailsEN],[Discount],[GenreId],[Name],[Picture],[PublisherId],[Pages],[Price],[Published],[Quantity]) 
VALUES(10,N'Agatha Christie''s most famous murder mystery, reissued with a striking new cover designed to appeal to the latest generation of Agatha Christie fans and book lovers. Just after midnight, a snowdrift stops the Orient Express in its tracks. The luxurious train is surprisingly full for the time of the year, but by the morning it is one passenger fewer. An American tycoon lies dead in his compartment, stabbed a dozen times, his door locked from the inside. Isolated and with a killer in their midst, detective Hercule Poirot must identify the murderer - in case he or she decides to strike again. ',0,7,N'Murder on the Orient Express',N'images/books/murderOnTheOrientExpress.jpg',5,0,PAGES,1000,1,15);

INSERT INTO [dbo].[Books] ([AuthorId],[DetailsEN],[Discount],[GenreId],[Name],[Picture],[PublisherId],[Pages],[Price],[Published],[Quantity]) 
VALUES(10,N'Agatha Christie''s world-famous mystery thriller, reissued with a striking new cover designed to appeal to the latest generation of Agatha Christie fans and book lovers. Ten strangers, apparently with little in common, are lured to an island mansion off the coast of Devon by the mysterious U.N.Owen. Over dinner, a record begins to play, and the voice of an unseen host accuses each person of hiding a guilty secret. That evening, former reckless driver Tony Marston is found murdered by a deadly dose of cyanide. The tension escalates as the survivors realise the killer is not only among them but is preparing to strike again... and again...',0,7,N'And Then There Were None',N'images/books/andThenThereWereNone.jpg',5,224,1000,1,15);

INSERT INTO [dbo].[Books] ([AuthorId],[DetailsEN],[Discount],[GenreId],[Name],[Picture],[PublisherId],[Pages],[Price],[Published],[Quantity]) 
VALUES(10,N'Agatha Christie''s most exotic murder mystery, reissued with a striking new cover designed to appeal to the latest generation of Agatha Christie fans and book lovers. The tranquillity of a cruise along the Nile is shattered by the discovery that Linnet Ridgeway has been shot through the head. She was young, stylish and beautiful, a girl who had everything - until she lost her life. Hercule Poirot recalls an earlier outburst by a fellow passenger: `I''d like to put my dear little pistol against her head and just press the trigger.'' Yet in this exotic setting'' nothing is ever quite what it seems... ',0,7,N'Death on the Nile',N'images/books/deathOnTheNile.jpg',5,256,1000,1,15);